### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by seichris** [seichris/issues-to-website2#7]
- [ ] opening/editing/closing issue triggers script
- [ ] script saves all issues into `issues.md`
- [ ] create one file per issue https://github.com/mattduck/gh2md/issues/13
- [ ] format should be in format for https://github.com/seichris/issues-to-website:

```
---

slug: 10
title: This bug is critical
description: >-
    Oh my. Better work out this one.
date: 2020-11-22T19:14:56.000Z
category: bug
state: proposed
url: https://github.com/seichris/issues-to-website/issues/10

----

##issue body

issue body
```
